import React from "react";

export const arraySpecialties = [
  { name: "Alergia/Imunologia" },
  { name: "Angiologia  " },
  { name: "Cardiologia" },
  { name: "Cirurgia Geral" },
  { name: "Cirurgia Pediátrica" },
  { name: "Cirurgia Plástica" },
  { name: "Clínica Médica" },
  { name: "Dermatologia" },
  { name: "Doenças Infecto-Parasitárias" },
  { name: "DST/AIDS" },
  { name: "Endocrinologia" },
  { name: "CFisiatria/Medicina Esportiva" },
  { name: "Fonoaudiologia" },
  { name: "Gastroenterologia" },
  { name: "Genética" },
  { name: "Geral" },
  { name: "Geriatria" },
  { name: "Ginecologia" },
  { name: "Hematologia" },
  { name: "Homeopatia, Acupuntura e Similares" },
  { name: "Medicina Preventiva e Social" },
  { name: "Medicina do Trabalho" },
  { name: "Nefrologia" },
  { name: "Neurologia" },
  { name: "Nutrição e Dietética" },
  { name: "Obstetrícia" },
  { name: "Odontologia" },
  { name: "Oftalmologia" },
  { name: "Oncologia" },
  { name: "Otorrinolaringologia" },
  { name: "Pediatria" },
  { name: "Psicologia" },
  { name: "Pneumologia/Tisiologia" },
  { name: "Proctologia" },
  { name: "Psiquiatria" },
  { name: "Reumatologia" },
  { name: "Urologia" },
  { name: "Neurocirurgia" },
  { name: "Análises Clínicas" },
  { name: "Anatomia Patológica/Citologia" },
  { name: "Atenção Psicossocial/Psicoterapia" },
  { name: "Eletrocardiografia" },
  { name: "Eletroencefalografia" },
  { name: "Endoscopia" },
  { name: "Fisioterapia/Reabilitação" },
  { name: "Fonoaudiologia" },
  { name: "Hemodinâmica" },
  { name: "Medicina Nuclear" },
  { name: "Quimioterapia" },
  { name: "Radiologia" },
  { name: "Radioterapia" },
  { name: "Ressonância Magnética" },
  { name: "Terapia Renal Substitutiva (Diálise)" },
  { name: "Tomografia Computadorizada" },
  { name: "Ultra-sonografia" },
];
export const arrayBasic = [
  { name: "Atenção ao parto por parteiras" },
  { name: "Saúde bucal por dentista" },
  { name: "Saúde bucal por técnico" },
  { name: "Atendimento por agente de saúde" },
  { name: "Atendimento por atendente de enfermagem" },
  { name: " Atendimento por enfermagem" },
  { name: "Atendimento médico básico continuado" },
  { name: " Atendimento básico intermitente" },
  { name: "Atendimento por médico de família (PSF)" },
  { name: "Controle de endemias e roedores (ratos)" },
  {
    name: "Controle de endemias/vetores (malária, dengue, chagas etc.)",
  },
  { name: " Controle de zoonoses/vacinação animal (raiva)" },
  { name: "Imunização básica (PNI)" },
  { name: "Imunização específica (febre amarela)" },
  { name: "Vigilância ambiental (saneamento)" },
  { name: "Vigilância epidemiológica" },
  { name: "Vigilância sanitária" },
];
